# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fastnntr_wrappers", use_symbols = TRUE, package_name = "fastnntr")

#' @usage NULL
#' @useDynLib fastnntr, .registration = TRUE
NULL

run_neighbornet_networx <- function(x, labels, flip_y) .Call(wrap__run_neighbornet_networx, x, labels, flip_y)

run_neighbournet_networx <- function(x, labels, flip_y) .Call(wrap__run_neighbournet_networx, x, labels, flip_y)


# nolint end
