# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fastnntr_wrappers", use_symbols = TRUE, package_name = "fastnntr")

#' @usage NULL
#' @useDynLib fastnntr, .registration = TRUE
NULL

set_fastnnt_threads <- function(threads) .Call(wrap__set_fastnnt_threads, threads)

run_neighbornet_networkx <- function(x, flip_y = TRUE, labels = NULL, max_iterations = 5000, ordering_method = NULL) .Call(wrap__run_neighbornet_networkx, x, flip_y, labels, max_iterations, ordering_method)

run_neighbournet_networkx <- function(x, flip_y = TRUE, labels = NULL, max_iterations = 5000, ordering_method = NULL) .Call(wrap__run_neighbournet_networkx, x, flip_y, labels, max_iterations, ordering_method)


# nolint end
