[package]
name = "fastnnt-r"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
extendr-api = "0.8.1"
ndarray = "0.16.1"
anyhow = "1"

fast_nnt_core = { package = "fast-nnt", path = ".." } 